### ISSUE TITLE
Manifest for Kubernetes deployment or job

### ISSUE THREAD

**Issue by denist-huma** [dmolesUC/cos#22]

**Comment by dmolesUC** [comment]
This is covered by #20 as well, correct?

**Comment by denist-huma** [comment]
Hey David
Nice to meet you online.
No on this ticket you make horses go gallop. :) this gonna be my next PR
goal.

I have started but it isn't complete yet. :+1:

пт, 24 сент. 2021 г., 20:03 David Moles ***@***.***>:
